application: connection-speed-demo
api_version: 1
runtime: python27
threadsafe: true
version: 1

handlers:
- url: /static
  static_dir: static
- url: /task/.*
  script: main.application
  login: admin
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
